No longer mark AbstractFactory as internal
Roave/psr-container-doctrine pull request #140
Opened 2024-10-29 13:36 UTC by cspray

If a factory is used and it requires a key other than 'orm_default' you must construct and invoke the factory yourself. Doing so will invoke methods marked as internal, causing tooling to erroneously mark using this factory as invalid. This patch removes the internal annotation, allowing the AbstractFactory to be used to customize the configuration key without triggering internal method usage.

Fixes #139

2024-10-29 13:38 UTC, Slamdunk requested changes

2024-10-29 13:38 UTC, Slamdunk commented on src/AbstractFactory.php
>   *
```suggestion
```

2024-10-29 13:41 UTC, Slamdunk approved these changes

2024-10-29 13:41 UTC, merged

2024-11-08 16:42 UTC, Ocramius commented
Note: this change is not part of the `5.3.1` release, because it targeted `5.4.0`.

We can change the Milestone here to `5.4.0` and close it, and it will re-tag it correctly.

2024-11-08 16:44 UTC, Slamdunk commented
Ouch, I'm sorry :see_no_evil: 

I'll do it next week :+1:

2024-11-08 16:45 UTC, Ocramius commented
@Slamdunk if you want, I can do it from here, depends on whether you're fine with just rolling `5.4.0`